### ISSUE TITLE
It seems that the access of Google Drive to download the pretrained models is not available

### ISSUE THREAD

**Issue by callous-youth** [Trustworthy-AI-Group/RPA#1]
Thanks for sharing the training code for this work. Whereas, it seems that the access of Google Drive to download the pretrained models is not available. Could the authors fix this issue or provide a new link to download these pretrained models? Thanks very much.

**Comment by TongKangheng** [comment]
We're very sorry for the trouble this has caused you. We have fixed this problem, please try downloading again.
