### ISSUE TITLE
Request for defense method HGD and NRP model files

### ISSUE THREAD

**Issue by YtengTan** [Trustworthy-AI-Group/RPA#3]
Dear authors,

Thanks for the open-source of your neurips23 paper _Rethinking the Backward Propagation for Adversarial Transferability_!

While I try to reproduce the results in Table 3 -- defense methods evaluation of BPA. I found the model files for defense methods **HGD and NRP** are not provided in this code repository.

It would be very helpful if you could provide these two files.

Thank you!

**Comment by xiaosen-wang** [comment]
please refer to this repo: https://github.com/Trustworthy-AI-Group/TransferAttack
